### ISSUE TITLE
Script fails with "Struct size mismatch" error

### ISSUE THREAD

**Issue by matthill** [FabAlchemy/ssl-snitch#1]
I tried running this script on Ubuntu 22.04 64-bit.   SSL version is 3.0.2-0

sudo bpftrace ssl-snitch.bt

    BUG: [/home/runner/work/bpftrace/bpftrace/src/ast/passes/codegen_llvm.cpp:1937] Struct size mismatch: expected: 28, real: 26
    Aborted

**Comment by fabalchemy** [comment]
Hello,

Thanks for reporting this issue. I'd like to point out this script was developed as part of an interviewing process and simply serves as a proof of concept.

I looked into this and believe the issue is linked to https://github.com/iovisor/bpftrace/issues/1332 (the code already had a hack for this). Apparently, pre-allocating the `$dport` variable fixes LLVM's weird handling of misaligned accesses. 

I've created a MR so you can try it :). 

PS: I also came across a [problem with the Ubuntu package for `bpftrace`](https://bugs.launchpad.net/ubuntu/+source/bpftrace/+bug/1969625). The binary is stripped, so it fails to handle the `BEGIN` probe. I suggest you use the latest version from the [repo](https://github.com/iovisor/bpftrace).

**Comment by matthill** [comment]
Thanks, Fabien.  Solid job on an interview assignment!
